# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lsgwr.github.io
date_format: "ordinal"
title: 空無一悟
subtitle: "微信公众号：空無一悟"
description: "个人博客，公众号：空無一悟"
keywords: lsgwr, oneline-exam, 空無一悟
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: lsgwr/lsgwr.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: lsgwr
organization: 
organization_url: 
github_username: lsgwr
location: Shanghai, China
email: 1648266192@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /open-source/
    label: 开源

#   -
#     href: /wiki/
#     label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
